package com.royware.corona.dashboard.enums.dashstats;

public enum DashStatsTypes {
	DASHSTATS_BY_US_TOTALS,
	DASHSTATS_REGION_CASES,
	DASHSTATS_REGION_CASES_MOVING_SUM,
	DASHSTATS_REGION_DEATHS,
	DASHSTATS_REGION_DEATHS_MOVING_SUM,
	DASHSTATS_REGION_VACC,
	DASHSTATS_US_REGIONS_BY_TESTING,
	DASHSTATS_US_REGIONS_PROPORTIONS,
	DASHSTATS_PER_CAPITA_STATS
}
