package com.royware.corona.dashboard.enums.charts;

public enum ChartTypes {
	CASES_DAILY_AND_TOTAL_VERSUS_TIME,
	CASES_RATE_OF_CHANGE_VERSUS_TIME,
	CASES_ACCELERATION_VERSUS_TIME,
	CASES_CHANGE_VERSUS_CASES,
	CASES_AS_FRAC_OF_POP_VERSUS_TIME,
	CASES_TO_TESTS_RATIO_VERSUS_TIME,
	DEATHS_DAILY_AND_TOTAL_VERSUS_TIME,
	DEATHS_RATE_OF_CHANGE_VERSUS_TIME,
	DEATHS_ACCELERATION_VERSUS_TIME,
	DEATHS_CHANGE_VERSUS_DEATHS,
	DEATHS_AS_FRAC_OF_POP_VERSUS_TIME,
	HOSP_NOW_VERSUS_TIME,
	HOSP_TOTAL_VERSUS_TIME,
	TESTS_DAILY_AND_TOTAL_VERSUS_TIME,
	VACC_DAILY_AND_TOTAL_VERSUS_TIME,
}
